# Generated by Django 2.2.6 on 2019-12-19 03:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateField(verbose_name='event date')),
                ('time', models.TimeField(verbose_name='event time')),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=2000)),
                ('attendees', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), size=None)),
                ('infolink', models.CharField(max_length=1000)),
            ],
        ),
    ]
